### ISSUE TITLE
Missing data preprocessing scripts

### ISSUE THREAD

**Issue by Jimlee079** [vision-agh/mt_kria#5]
Hi, I'm trying on trying Multi-task V3' model, but can't found 'bdd_to_yolo.py' and './data/labels.py' two scripts mentioned in the 'Training Dataset preparation' part in both this repo and the AMD's original repo.  

I had collected the 'bdd_to_yolo.py' in this [repo](https://github.com/kevin840307/Embedded-YOLO), but these is nowhere I can found the './data/labels.py'. I think is to select the seg classes used for training the model, could you please make it clear that which classes are used to train the seg branch? Thank you!

**Comment by maciekbaczmanski** [comment]
Hi @Jimlee079 . We've stumbled across the same problem with original repository and reported it to the authors, but unfortunately didn't get any response (https://github.com/Xilinx/Vitis-AI/issues/1154). Fixes in this repository support only training and deploying the model. We do not support scripts for dataset creation as we have created the dataset manually, according to filetree from [README.md](https://github.com/vision-agh/mt_kria#preparation).

If you wish, I can try to upload sample dataset at the beginning of next week.

**Comment by Jimlee079** [comment]
Hi @maciekbaczmanski , thanks for the reply, I think a list of which 16 seg classes in the cityscapes all 19 seg classes are used for seg branch training could solve my question, no need for the full data processing scripts. and some sample dataset will be better!

**Comment by maciekbaczmanski** [comment]
Hi @Jimlee079. Sorry it took so long. Here is a PR: https://github.com/vision-agh/mt_kria/pull/7
Actually for training, number of classes is set here: https://github.com/vision-agh/mt_kria/blob/64cdc83360444c16dd63e481321f9d8f6a41be58/code/train/data/config.py#L38C9-L38C9
it should be 1 more than actual number of classes to include background. Brightness of each pixel assigns it to each class. Cityscapes classes are used here only for visualization, while dataset should be in grayscale.

**Comment by Jimlee079** [comment]
hi@maciekbaczmanski, nevermind, the samples helps a lot, thanks for that!
