### ISSUE TITLE
Missing detail training procedure

### ISSUE THREAD

**Issue by pdoublerainbow** [vision-agh/mt_kria#6]
Hi, thanks for your open source. I would like to know the detail training procedure. 
For example, there are five subtasks here, did you train the network all the subtasks at the same time, or you just train some tasks at first step, then train the left subtasks. If you choose the second choice, would you please give me some sign how to step by step to train a good performance weights.

**Comment by maciekbaczmanski** [comment]
Hi @pdoublerainbow. For our papers we have trained all subtasks at the same time. 
If you wish to train subtasks separately, you should be able to use fine-tuning:
https://github.com/vision-agh/mt_kria/blob/64cdc83360444c16dd63e481321f9d8f6a41be58/code/train/train.py#L78
And backbone fine-tuning: `args.finetune_bb`. We have unfortunately not tested which way of training this way is the most efficient.
